name: Save Weather JSON

on:
  schedule:
    - cron: "0 * * * *" # 매 시간 정각
  workflow_dispatch:

jobs:
  fetch_weather:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Python Dependencies
        run: |
          pip install -r requirements.txt

      - name: Install Chromium
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser

      - name: Run Weather Scraper
        run: python naver_weather_scraper.py

      - name: Commit and Push JSON
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add data.json
          git commit -m "자동 저장: 날씨 JSON 추가" || echo "No changes"
          git push
